### ISSUE TITLE
claim names when using a channel

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/spee.ch#196] opened 2017-10-11 23:42 UTC
Shouldn't we allow any claim name when creating uploads under a channel? The channel resolution should always make sure the claim is unique. 

Right now it seems like the same claim check rules which return "Sorry, that url ending has been taken" are the same with or without a channel

**Comment by kauffj** [comment] 2017-10-12 19:27
@tzarebczan this is blocked by `lbry` preventing two claims to the same name. Not a choice of spee.ch. Should be filed on `lbry` if it isn't already.

**Comment by MSFTserver** [comment] 2017-10-12 20:18
if its on the lbry side then should it be throwing this error for the app to?

**Comment by tzarebczan** [comment] 2017-10-12 20:28
@kauffj lbry does allow publishing to a claim name that is taken if you are publishing via a channel or publishing via command line.

**Comment by kauffj** [comment] 2017-10-13 17:28
@MSFTserver @tzarebczan I believe the issue is that the daemon treats a second publish to the same name for a given wallet as an edit regardless of channel, but this ought to be tested.

@tzarebczan can you try publishing to the same name under two different channels (or one with channel and one anonymous) and confirm?

**Comment by tzarebczan** [comment] 2017-10-16 23:49
Just can through this and you are right - treats the 2nd publish as an update.  Always saw the option so assumed it would work but never tried it! 

First publish(jiggytom channel):
```
2017-10-16 19:36:49,680 INFO     lbrynet.daemon.Daemon:1908: Publish: {'claim_address': None, 'name': u'testpub-01', 'bid': 0.01, 'claim_dict': {'version': '_0_0_1', 'claimType': 'streamType', 'stream': {'version': '_0_0_1', 'metadata': {u'language': u'en', u'license': u'', u'title': u'test pub1', 'version': '_0_1_0', u'nsfw': False, u'licenseUrl': None}}}, 'file_path': u'C:\\Users\\thoma\\Downloads\\exodus-windows-x64-1.35.5.exe', 'change_address': None}
2017-10-16 19:36:51,193 INFO     lbrynet.daemon.Publisher:27: Starting publish for testpub-01
2017-10-16 19:37:12,115 INFO     lbrynet.core.Wallet:949: Saving metadata for claim 77d597d36be0441d70ac90bd08264fbb6e7152a40d9fdc1d13bfbd3eb7ac94bd 0
2017-10-16 19:37:12,690 INFO     lbrynet.daemon.Daemon:716: Success! Published to lbry://testpub-01 txid: 77d597d36be0441d70ac90bd08264fbb6e7152a40d9fdc1d13bfbd3eb7ac94bd nout: 0
```
https://explorer.lbry.io/tx/77d597d36be0441d70ac90bd08264fbb6e7152a40d9fdc1d13bfbd3eb7ac94bd

2nd publish (thomaszarebczan channel):
```
2017-10-16 19:38:42,660 INFO     lbrynet.core.Wallet:823: Resolving lbry://@thomaszarebczan/testpub-01
2017-10-16 19:38:43,210 ERROR    lbryum.commands:1164: No valid claims for this name for this channel
2017-10-16 19:38:43,210 ERROR    lbryum.commands:1164: No valid claims for this name for this channel
2017-10-16 19:39:17,664 INFO     lbrynet.daemon.Daemon:1908: Publish: {'claim_address': None, 'name': u'testpub-01', 'bid': 0.01, 'claim_dict': {'version': '_0_0_1', 'claimType': 'streamType', 'stream': {'version': '_0_0_1', 'metadata': {u'language': u'en', u'license': u'', u'title': u'test pub 2', 'version': '_0_1_0', u'nsfw': False, u'licenseUrl': None}}}, 'file_path': u'C:\\Users\\thoma\\Downloads\\exodus-windows-x64-1.35.5.exe', 'change_address': None}
2017-10-16 19:39:18,999 INFO     lbrynet.daemon.Publisher:27: Starting publish for testpub-01
2017-10-16 19:39:48,628 INFO     lbrynet.core.Wallet:949: Saving metadata for claim 94fcd6ceade6107ee8a5b8677f758ce728d871135c8fee1bbba7b62e1778a72e 0
2017-10-16 19:39:49,165 INFO     lbrynet.daemon.Daemon:716: Success! Published to lbry://testpub-01 txid: 94fcd6ceade6107ee8a5b8677f758ce728d871135c8fee1bbba7b62e1778a72e nout: 0
```
https://explorer.lbry.io/tx/94fcd6ceade6107ee8a5b8677f758ce728d871135c8fee1bbba7b62e1778a72e

**Comment by billbitt** [comment] 2017-11-13 23:07
closing because duplicative of #200

**Closed by billbitt** 2017-11-13 23:07 UTC
