### ISSUE TITLE
XHR API usage along with CURL

### ISSUE THREAD

**Issue by esteem8** [lbryio/spee.ch#368] opened 2018-03-03 04:43 UTC
Internet browsers can't use CURL queries, only server can use CURL.

When trying to use XHR queries in JS, the query fail and the browser notify `No 'Access-Control-Allow-Origin' header is present on the requested resource.` which means that the API is free and unlimited but only designed for server side usage.

Could change the API page's header be possible in order to enable client-side JavaScript usage or might providing a proxy/server should be required?

**Comment by billbitt** [comment] 2018-03-21 19:08
closing because this issue is duplicate of https://github.com/lbryio/spee.ch/issues/368 and https://github.com/lbryio/spee.ch/issues/365

**Closed by billbitt** 2018-03-21 19:08 UTC
Labels: needs: triage

**Comment by esteem8** [comment] 2018-04-06 15:56
Leaved a comment on #365 ;)
