### ISSUE TITLE
Wrong filename when saving image

### ISSUE THREAD

**Issue by lyoshenka** [lbryio/spee.ch#174] opened 2017-09-28 13:53 UTC
![](https://i.imgur.com/sTa73Xe.png)

Look at https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition

**Comment by lyoshenka** [comment] 2017-09-28 13:55
Or maybe its that the content-type of the whole page is html, not png?

**Comment by MSFTserver** [comment] 2017-09-28 15:06
what browser i cant seem to reproduce this chrome gives the .png for both save image and save link as

**Comment by billbitt** [comment] 2017-11-07 15:41
I am closing this because I cannot reproduce.  File names work fine for me; I believe this was a result of trying to save the whole page rather than the image.

**Closed by billbitt** 2017-11-07 15:41 UTC
