### ISSUE TITLE
publish in a channel does not show up immediately

### ISSUE THREAD

**Issue by billbitt** [lbryio/spee.ch#479] opened 2018-06-14 21:16 UTC
If a publish is made into a channel, it does not show up until the client refreshes the app.  I believe this is because the redux store already retrieved the channel's info, including the list of claims, so it is not making a new request.  After a successful publish, the asset record needs to be added to the channel's claims array or else the channel's info needs to be refreshed in full.

**Comment by kauffj** [comment] 2018-08-06 13:27
@billbitt should this be tagged Osprey? Not sure how important this is

**Comment by tzarebczan** [comment] 2018-10-10 20:48
@skhameneh this is the issue I mentioned and it's still happening. It may be important to fix for Osprey.

**Comment by kauffj** [comment] 2018-10-11 19:28
If new publishes don't show up without hitting reload, this probably should be fixed for Osprey.

**Comment by tzarebczan** [comment] 2018-10-29 23:08
Looks like it doesn't get added until it's confirmed + refreshed.

**Comment by tiger5226** [comment] 2018-11-04 01:47
@daovist Chainquery has been updated to process mempool transactions. It regularly checks for these every second and processes them. See https://github.com/lbryio/chainquery/issues/59 for added details.

**Comment by daovist** [comment] 2018-11-05 13:38
Excellent! Thank you @tiger5226

**Comment by skhameneh** [comment] 2018-11-10 00:08
During testing this gave a very acceptable update time (few seconds); we will actively work on improving times.  Closing for now.

**Closed by skhameneh** 2018-11-10 00:08 UTC
Labels: Osprey, level: 3, type: bug
