### ISSUE TITLE
User feedback when copying URLs

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/spee.ch#542] opened 2018-07-25 18:38 UTC
When you click into the share boxes on a spee.ch claim page, the URLs are automatically copied. Should receive some on-screen feedback that this happened.

**Comment by billbitt** [comment] 2018-08-07 17:42
closing because duplicate of https://github.com/lbryio/spee.ch/issues/509

**Closed by billbitt** 2018-08-07 17:42 UTC
Labels: needs: triage, type: improvement
