### ISSUE TITLE
Landscape image shows preview in portrait mode

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/spee.ch#540] opened 2018-07-20 17:30 UTC
Spee.ch URL: https://spee.ch/0/Lbry-c-swag

Twitter post: https://twitter.com/TomZarebczan/status/1020349594293719041?s=19

It also did this on FB and Discord. Slack somehow unfurled correctly. 

This image was taken in landscape mode mode on a Samsung Galaxy S8+ via the default camera app.

**Comment by jessopb** [comment] 2019-01-11 03:18
duplicate of https://github.com/lbryio/spee.ch/issues/435: exif image orientation data.

**Closed** 2019-01-15 18:56 UTC
Labels: level: 2, type: bug
