### ISSUE TITLE
Slow load time for videos/claims opened the first time

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/spee.ch#214] opened 2017-10-24 03:27 UTC
Looks like speech tries to do a get immediately when a new claim is encountered that hasn't been downloaded. This results in a long wait while speech tries to download the blob files. If the blobs fail, you get an plaintext timeout (there's a separate issue for this). If it works, you finally get the claim page with the ability to start the video. 

Would it be possible to show the claim page on speech and use a resolve to populate the information and then start downloading the file. This would be a good time to show a status of the download - whether it started, percentage, etc.

**Comment by billbitt** [comment] 2017-11-09 23:40
excellent.  thanks @tzarebczan

**Comment by billbitt** [comment] 2017-11-13 22:08
related to #63

**Comment by billbitt** [comment] 2017-11-27 16:28
Story: As a user, I want the page I request to be displayed as quickly as possible, even if I am told that some content still needs to load.

Problem: if content is not currently available on spee.ch, spee.ch is making a get through the daemon and then waiting for that get request to return before responding to the client's request.

Solution: In the case of show pages, spee.ch should return the page itself as soon as is possible (i.e. once it has resolved the request against the db and knows that there is a valid claim), and then it can start to retrieve the asset itself. If this is done, then this will allow the client to better display the status of the request. I.e. it can show an intermediate loading message, and it can update the client if something goes wrong like the sd blob can't be found or not enough peers are present, etc.
(note: if expose more api endpoints for daemon, like peer_list, then the client can display how many peers etc., which would be super cool).

**Comment by kauffj** [comment] 2017-12-12 14:34
@billbitt I'm closing this since #276 is merged, but please confirm it had the desired effect.

**Closed by kauffj** 2017-12-12 14:34 UTC

**Comment by billbitt** [comment] 2017-12-12 15:02
confirmed
