### ISSUE TITLE
URLs that are valid claims but have wrong short channel ids should provide better feedback to the user

### ISSUE THREAD

**Issue by kauffj** [lbryio/spee.ch#328] opened 2018-01-22 18:43 UTC
Works:
- https://spee.ch/@lbry:3fda836a92faaceedfe39822/thinkaboutit
- https://spee.ch/@lbry:3f/thinkaboutit
- https://spee.ch/@lbry/thinkaboutit

Doesn't Work:
- https://spee.ch/@lbry:3/thinkaboutit

**Comment by billbitt** [comment] 2018-01-26 19:41
So, the url is actually resolving correctly.  The issue is that `3` is the short id for the `@lbry` certificate with claim id `3aae09b13b6426070b536b90167dfe6a3fc40851`.  Therefore, it is accurate that there is no claim for `thinkaboutit` at  `spee.ch/@lbry:3/thinkaboutit`.  

The proper short id for the `@lbry' channel with the claim id `3fda836a92faaceedfe398225fb9b2ee2ed1f01a`, which actually owns the `thinkaboutit` claim, is `3f` because that certificate claim came later in time. 

@kauffj What is the ideal solution for this?  At minimum it would helpful to give a more specific message that a channel was found, but there is no matching claim in that particular channel.  The truly ideal result for this situation would probably be to redirect the user to a matching url.  E.g. redirect from `spee.ch/@lbry:3/thinkaboutit` -> `spee.ch/@lbry:3f/thinkaboutit`.  This would require searching the other channels with the same claim name for matching claims

**Comment by kauffj** [comment] 2018-01-26 20:02
Ah, makes sense. Yes, this could probably be handled by suggesting alternatives (I wouldn't auto-redirect), but it's pretty low priority.

**Comment by alyssaoc** [comment] 2018-12-07 18:21
closing, reopen if demand increases

**Closed by alyssaoc** 2018-12-07 18:21 UTC
Labels: level: 3, type: bug
