### ISSUE TITLE
Spee.ch blockchain database: Claim records with a 'certificate Id' but no 'channel name' need to be updated

### ISSUE THREAD

**Issue by kauffj** [lbryio/spee.ch#334] opened 2018-01-26 01:33 UTC
story: As a user, when I visit the details page for a piece of content that is published in a channel, I want to see the channel name that that content is published in, so that I can easily find other content from that channel.

problem: some content that is published in a channel does not show the channel on the details page.  Example: https://spee.ch/b1af78a930d5eccf22f47a0a09899834f5ca0806/casually-flirting is published to the @casuallyexplained channel, but doesn't show the channel name.

**Comment by billbitt** [comment] 2018-02-05 20:25
note: this issue may be solved by https://github.com/lbryio/spee.ch/pull/343

**Comment by billbitt** [comment] 2018-03-12 17:44
I've been looking into this and the issue is a result of the relational db not having the channel names for these claims.  This is an issue with the sync tool.  I believe it is fixed in the sync tool, because dev1.spee.ch has the proper info in its database.  So, the solution wrt spee.ch is to re-sync the chain from the beginning or write a tool to update the affected records.  I started writing a task for this but it it timing out when the number of claims to update gets too large, so it needs to be updated to have some sort of throttle.

**Comment by billbitt** [comment] 2018-03-12 17:48
To clarify the above comment: this is an issue with the data in dabase of the production version of spee.ch not an issue with the spee.ch codebase.  I updated the title of this issue to reflect what really needs to be done to solve this: Claim records in spee.ch's mysql db with a 'certificate Id' but no 'channel name' need to be updated.

**Comment by billbitt** [comment] 2018-05-29 17:50
this should be fixed/moot when we switchto chainquery

**Closed by billbitt** 2018-05-29 17:50 UTC
Labels: level: 2, type: improvement
